name: Test Backend
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run service
        run: |
          cd backend
          ./gradlew run &
          echo $! > server_pid
          
          for i in {1..30}; do
            if curl -fs http://localhost:3000; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server to start..."
            sleep 2
          done
          echo "Server did not start in time." >&2
          exit 1

      - name: Stop service
        run: kill $(cat server_pid) || true
