name: Test Backend
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run service
        run: |
          ./gradlew run
          echo $! > server_pid
          sleep 10

      - name: Verify service status
        run: |
          curl -f http://localhost:8820 || exit 1

      - name: Stop service
        if: always()
        run: |
          kill $(cat server_pid) || true
